name: repouch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.17.0
  motion_tab_bar_v2: ^0.3.0
  shared_preferences: ^2.0.11
  table_calendar: ^3.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/wallet.png
    - assets/moneypage.png
    - assets/maintext.png